# Generated by Django 4.0.3 on 2022-05-11 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carte', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.BigIntegerField()),
                ('cash', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('metadata', models.TextField(blank=True, null=True)),
                ('transaction_id', models.SlugField(default=uuid.uuid4, editable=False)),
                ('operator_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('api_response_id', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.carte')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.fiche')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=50)),
                ('date_remboursement', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
