# Generated by Django 4.0.3 on 2022-05-11 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carte', '0001_initial'),
        ('payment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_operation', models.CharField(choices=[('ATTENTE', 'En Attente'), ('ACCEPTE', 'Accepté'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='ATTENTE', max_length=15)),
                ('montant_initial', models.BigIntegerField(blank=True, null=True)),
                ('frais_operation', models.CharField(blank=True, max_length=20, null=True)),
                ('montant_operation', models.BigIntegerField(blank=True, null=True)),
                ('identifiant', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carte.carte')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.fiche')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operation.typeoperation')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='FraisOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_fee', models.CharField(choices=[('montant', 'Montant'), ('pourcentage', 'Pourcentage')], default='montant', max_length=15, verbose_name="Frais d'operation")),
                ('buy_carte_amount', models.FloatField(blank=True, null=True, verbose_name="Montant à l'achat de la carte")),
                ('initial_amount_value', models.FloatField(blank=True, null=True, verbose_name='montant initial')),
                ('final_amount_value', models.FloatField(blank=True, null=True, verbose_name='montant final')),
                ('amount_value', models.FloatField(blank=True, null=True, verbose_name='montant frais')),
                ('percentage_value', models.FloatField(blank=True, null=True, verbose_name='valeur du pourcentage')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False)),
                ('date_addee', models.DateTimeField(auto_now_add=True)),
                ('carte_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carte.typecarte', verbose_name='type de carte')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.typeoperation', verbose_name="type d'operation")),
            ],
            options={
                'ordering': ('operation_type',),
            },
        ),
    ]
