# Generated by Django 4.0.3 on 2022-05-11 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='types_cartes/', verbose_name='logo')),
                ('rechargement_url', models.URLField(default='https://www.gtpportal.com/Visa/MerchantLite/UserLogin.aspx?ReturnUrl=%2fVisa%2fMerchantLite', verbose_name='lien de rechergement')),
                ('plafond', models.BigIntegerField(blank=True, default=2000000, null=True, verbose_name='nom')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('carte_client_id', models.BigIntegerField(unique=True, verbose_name='identifiant client')),
                ('carte_num', models.BigIntegerField(unique=True, verbose_name='numéro de carte')),
                ('carte_exp_month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, 10), (11, 11), (12, 12)], default=1, verbose_name="mois d'expiration")),
                ('carte_exp_year', models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041)], default=2022, verbose_name="année d'expiration")),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile', verbose_name='Créateur')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.fiche', verbose_name='propriétaire')),
                ('type_carte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carte.typecarte', verbose_name='Type de carte')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
