# Generated by Django 4.0.3 on 2022-05-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='carte_client_id',
            field=models.CharField(max_length=11, unique=True, verbose_name='identifiant client'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='carte_num',
            field=models.CharField(max_length=18, unique=True, verbose_name='numéro de carte'),
        ),
    ]
