# Generated by Django 4.0.3 on 2022-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_alter_carte_carte_client_id_alter_carte_carte_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecarte',
            name='buy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='achat'),
        ),
        migrations.AddField(
            model_name='typecarte',
            name='recharge',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='recharge'),
        ),
    ]
