# Generated by Django 4.0.3 on 2022-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_typecarte_buy_typecarte_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecarte',
            name='buy',
            field=models.BooleanField(default=False, verbose_name='achat'),
        ),
        migrations.AlterField(
            model_name='typecarte',
            name='recharge',
            field=models.BooleanField(default=False, verbose_name='recharge'),
        ),
    ]
